/**
 * Audio asset registry.
 *
 * The only place in the codebase that names a concrete audio file. Gameplay
 * refers to logical keys, so a file can be replaced, trimmed, or re-encoded
 * without touching a system (M2, audio architecture).
 *
 * Levels and pool sizes are **not** here: they live in `audioMix.ts`, and the
 * tracks themselves live in `musicCatalogue.ts`, because this module reaches
 * for files through Metro's `require` and therefore cannot be imported by a
 * `node --test` run at all (M16). Splitting them is what made the mix
 * assertable.
 *
 * Since M24A the catalogue also holds each track's **path**, which is what
 * `npm run measure:tempo` and the contract test read. That is not a second
 * source of truth — the path was already in three places, and a mirrored
 * constant is a constant that drifts. What stays here is the one thing that
 * cannot move: Metro resolves `require` statically, so the literal argument
 * below has to be written out. `tests/audioContract.test.ts` reads this file's
 * source and proves every catalogue path appears in it.
 *
 * Provenance is contracted by `assets/manifest/asset-manifest.json` and
 * `docs/assets/AUDIO-SOURCES.md`. The source MIDI is deliberately absent: it is
 * provenance only and there is no MIDI runtime (AGENTS.md rule 10).
 */

/*
 * Metro resolves bundled media through `require`; an ESM import of a .wav is
 * not equivalent, so this file is the one deliberate exception to the rule.
 */
/* eslint-disable @typescript-eslint/no-var-requires */

import type { SfxKey } from './audioMix.ts';
import type { MusicTrackId } from './musicCatalogue.ts';

export { MIX, SFX_POOL_SIZE, type SfxKey } from './audioMix.ts';
export type { MusicTrackId } from './musicCatalogue.ts';

export const MUSIC_SOURCES: Record<MusicTrackId, number> = {
  /**
   * The CC0 rock loop the game has always used.
   *
   * It is **at 120 BPM**, measured by aligning its own source MIDI's onset
   * train against the audio. The project recorded it for a long time as a
   * 90 BPM track that slipped 417 ms per loop, which was arithmetic on the
   * file's 21.75 s length rather than a measurement of its pulse.
   *
   * Against a 90 BPM clock that is not a drift but a cross-rhythm: four
   * musical beats to every three of the player's, coinciding once every two
   * seconds and 167 ms apart the rest of the time. It is fine on a stage where
   * no beat is scored and misleading on one where they are, so it now plays
   * only on Stage 1. See `docs/assets/AUDIO-SOURCES.md`.
   */
  showTheme: require('../../assets/audio/music/runtime/rock_theme_song_loop.wav'),
  /**
   * Generated by `scripts/make-show-bed.mjs`: exactly 32 beats at 90 BPM, and
   * a full arrangement rather than a floor — driven power chords, crashes on
   * the phrase heads, a fill into the loop point. It is what the show and the
   * encore play, and it exists because the CC0 loop above turned out to be at
   * 120 BPM rather than drifting at 90.
   */
  showBed: require('../../assets/audio/music/runtime/show_bed_90.wav'),
  /**
   * Generated by `scripts/make-groove-bed.mjs`: exactly 16 beats at 90 BPM,
   * with every tail wrapped back to the head so the loop is seamless.
   *
   * The tempo is correct *by construction* rather than by luck, which is the
   * only way to be sure a bed under a scored beat is not lying to the player.
   * Deliberately a bed and not a song — Stage 2 teaches the beat, and an
   * arrangement worth listening to buries the thing being taught.
   */
  grooveBed: require('../../assets/audio/music/runtime/groove_bed_90.wav'),

  /*
   * M24B audition candidates.
   *
   * Bundled, and unreachable. Metro resolves `require` statically, so a track
   * the game might play has to be named here at build time whatever gates sit
   * in front of it — which means "development-only" cannot be a bundling
   * property and is not implemented as one. It is enforced where selection
   * happens: `availableTracks(false)` never returns a candidate,
   * `parseSetlist` rejects a save that names one, and the audition screen is
   * behind `isDevelopmentBuild()`. `tests/audioContract.test.ts` and
   * `tests/setlist.test.ts` hold all three.
   *
   * Sixteen bars each at 90 BPM, conditioned from CC0 sources by
   * `scripts/build-candidates.mjs`. Every one is provenanced in
   * `docs/assets/AUDIO-SOURCES.md`; none may ship until the owner has heard it.
   */
  noRefunds: require('../../assets/audio/music/candidates/noRefunds_90.wav'),
  brokenAmp: require('../../assets/audio/music/candidates/brokenAmp_90.wav'),
  lastCall: require('../../assets/audio/music/candidates/lastCall_90.wav'),
  stageDive: require('../../assets/audio/music/candidates/stageDive_90.wav'),
  cheapBeerRiot: require('../../assets/audio/music/candidates/cheapBeerRiot_90.wav'),
  wrongChord: require('../../assets/audio/music/candidates/wrongChord_90.wav'),
  badSoundcheck: require('../../assets/audio/music/candidates/badSoundcheck_90.wav'),
  loadOut: require('../../assets/audio/music/candidates/loadOut_90.wav'),
  fireExit: require('../../assets/audio/music/candidates/fireExit_90.wav'),
  noEncore: require('../../assets/audio/music/candidates/noEncore_90.wav'),
  wrongVenue: require('../../assets/audio/music/candidates/wrongVenue_90.wav'),
};

export const SFX_SOURCES: Record<SfxKey, number> = {
  glassBreak: require('../../assets/audio/sfx/glass_breaking.wav'),
  stickWhoosh: require('../../assets/audio/sfx/stick_whoosh.wav'),
  impactThwack: require('../../assets/audio/sfx/impact_thwack.wav'),
  crowdApplause: require('../../assets/audio/sfx/crowd_applause.wav'),
  /*
   * Generated by `scripts/make-beat-click.mjs`, not downloaded (M16). An asset
   * this repository synthesizes has no licence to verify and no source page
   * that can go dead, which is the cleanest possible answer to rules 12-14 —
   * and it is 8 KB, which matters for a sound that plays ninety times a round.
   */
  beatClick: require('../../assets/audio/sfx/beat_click.wav'),
  /*
   * Generated by `scripts/make-mug-gulp.mjs`, not downloaded (M18), for the
   * same reasons as the click: no licence to verify, no source page to go
   * dead, and reproducible from a committed script.
   */
  mugDrink: require('../../assets/audio/sfx/mug_drink.wav'),
};
