/**
 * Audio asset registry.
 *
 * The only place in the codebase that names a concrete audio file. Gameplay
 * refers to logical keys, so a file can be replaced, trimmed, or re-encoded
 * without touching a system (M2, audio architecture).
 *
 * Levels, pool sizes and the tempo-lock table are **not** here: they live in
 * `audioMix.ts`, because this module reaches for files through Metro's
 * `require` and therefore cannot be imported by a `node --test` run at all
 * (M16). Splitting them is what made the mix assertable.
 *
 * Paths and provenance are contracted by `assets/manifest/asset-manifest.json`
 * and `docs/assets/AUDIO-SOURCES.md`. The source MIDI is deliberately absent:
 * it is provenance only and there is no MIDI runtime (AGENTS.md rule 10).
 */

/*
 * Metro resolves bundled media through `require`; an ESM import of a .wav is
 * not equivalent, so this file is the one deliberate exception to the rule.
 */
/* eslint-disable @typescript-eslint/no-var-requires */

import type { MusicKey, SfxKey } from './audioMix.ts';

export {
  MIX,
  MUSIC_TEMPO_LOCKED,
  SFX_POOL_SIZE,
  type MusicKey,
  type SfxKey,
} from './audioMix.ts';

export const MUSIC_SOURCES: Record<MusicKey, number> = {
  /**
   * The CC0 rock loop the game has always used.
   *
   * It is 21.75 s, which at 90 BPM is 32.625 beats — it slips about 417 ms per
   * loop and is in antiphase with the pad after two. That is fine on a stage
   * where no beat is scored and actively misleading on one where they are, so
   * it now plays only on Stage 1 and, until the owner picks a replacement, on
   * the show. See `docs/specs/M16-beat-clarity-and-progressive-teaching.md`.
   */
  showTheme: require('../../assets/audio/music/runtime/rock_theme_song_loop.wav'),
  /**
   * Generated by `scripts/make-groove-bed.mjs`: exactly 16 beats at 90 BPM,
   * with every tail wrapped back to the head so the loop is seamless.
   *
   * The tempo is correct *by construction* rather than by luck, which is the
   * only way to be sure a bed under a scored beat is not lying to the player.
   * Deliberately a bed and not a song — Stage 2 teaches the beat, and an
   * arrangement worth listening to buries the thing being taught.
   */
  grooveBed: require('../../assets/audio/music/runtime/groove_bed_90.wav'),
};

export const SFX_SOURCES: Record<SfxKey, number> = {
  glassBreak: require('../../assets/audio/sfx/glass_breaking.wav'),
  stickWhoosh: require('../../assets/audio/sfx/stick_whoosh.wav'),
  impactThwack: require('../../assets/audio/sfx/impact_thwack.wav'),
  crowdApplause: require('../../assets/audio/sfx/crowd_applause.wav'),
  /*
   * Generated by `scripts/make-beat-click.mjs`, not downloaded (M16). An asset
   * this repository synthesizes has no licence to verify and no source page
   * that can go dead, which is the cleanest possible answer to rules 12-14 —
   * and it is 8 KB, which matters for a sound that plays ninety times a round.
   */
  beatClick: require('../../assets/audio/sfx/beat_click.wav'),
  /*
   * Generated by `scripts/make-mug-gulp.mjs`, not downloaded (M18), for the
   * same reasons as the click: no licence to verify, no source page to go
   * dead, and reproducible from a committed script.
   */
  mugDrink: require('../../assets/audio/sfx/mug_drink.wav'),
};
